const cidadesBrasil = [
    'Anápolis',
    'Aracaju',
    'Belém',
    'Belo Horizonte',
    'Blumenau',
    'Boa Vista',
    'Brasília',
    'Campinas',
    'Campo Grande',
    'Cuiabá',
    'Curitiba',
    'Feira de Santana',
    'Flamengo',
    'Florianópolis',
    'Fortaleza',
    'Goiânia',
    'Indaiatuba',
    'João Pessoa',
    'Joinville',
    'Juiz de Fora',
    'Lajeado',
    'Londrina',
    'Maceió',
    'Macapá',
    'Manaus',
    'Marília',
    'Natal',
    'Niterói',
    'Palmas',
    'Piracicaba',
    'Porto Alegre',
    'Porto Velho',
    'Recife',
    'Ribeirão Preto',
    'Rio Branco',
    'Rio Claro',
    'Rio de Janeiro',
    'Salvador',
    'Santos',
    'São José dos Campos',
    'São Luís',
    'São Paulo',
    'Sorocaba',
    'Teresina',
    'Uberlândia',
    'Vitória'
  ];
  
  export default cidadesBrasil;
  